language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

install:
  - pip -q install -e .

script: 
    # test fortran-only "basic" program
    - cd build
    - cmake ..
    - make
    - cd ..
    
    # separately (previous 4 lines not needed) test python access to Glow
    - pytest -v

after_success:
  - coverage run tests/test_all.py
  - coveralls

