language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

env: FC=gfortran-6

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran-6

before_install:
  # temporary for pip < 9.1
  - pip -q install numpy

install: pip install -e .[tests]

script: pytest -v

after_success:
  - coverage run tests/test_all.py
  - coveralls

