language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

env: FC=gfortran-6

group: travis_latest

git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6

before_install:
  # temporary for pip < 9.1
  - pip -q install numpy
  
  - mkdir -p ~/.local/bin
  - ln -s /usr/bin/gfortran-6 ~/.local/bin/gfortran
  - export PATH="$HOME/.local/bin/:$PATH"

install: pip install -e .[tests]

script: 
  - make test

after_success:
  - coverage run tests/test_all.py
  - coveralls

